ARG UBUNTU_TAG=latest
FROM ubuntu:$UBUNTU_TAG
LABEL org.opencontainers.image.authors="Dileep Gadiraju"

#####Install Dependencies #####
RUN apt update
RUN apt install python ansible openssh-client vim iputils-ping -y

##### Generate SSH Key #####
RUN ["/bin/bash", "-c", "ssh-keygen -t rsa -N '' -f ~/.ssh/id_rsa <<< y"]